---
- name: Ensure yabai (MacOS)
  when: ansible_facts['os_family'] == 'Darwin' and homebrew_exists
  import_tasks: yabai.yml

- name: Ensure skhd (MacOS)
  when: ansible_facts['os_family'] == 'Darwin' and homebrew_exists
  import_tasks: skhd.yml


