---
- name: Ensure fastfetch (Debian)
  when: ansible_facts['os_family'] == "Debian"
  become: true
  ansible.builtin.apt:
    name: fastfetch
    state: present

- name: Ensure fastfetch (ArchLinux)
  when: ansible_facts['os_family'] == "Archlinux"
  become: true
  ansible.builtin.pacman:
    name: fastfetch
    state: present

- name: Ensure fastfetch (Darwin)
  when: ansible_facts['os_family'] == "Darwin"
  community.general.homebrew:
    name: fastfetch
    state: present

- name: Ensure fastfetch config directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/fastfetch"
    state: directory
    mode: "0755"

- name: Copy fastfetch config
  ansible.builtin.copy:
    src: config.jsonc
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/fastfetch/config.jsonc"
    mode: "0644"

- name: Copy fastfetch logo
  ansible.builtin.copy:
    src: logo.gif
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/fastfetch/logo.gif"
    mode: "0644"
