---
- name: Ensure common packages (MacOS)
  when: homebrew_exists | default(false)
  community.general.homebrew:
    name: "{{ common_packages }}"
    state: present

- name: Ensure MacOS-specific packages (MacOS)
  when: homebrew_exists | default(false)
  community.general.homebrew:
    name: "{{ darwin_common_packages }}"
    state: present
