---
- name: Create directory for docker GPG key (Debian)
  when: docker_exists.rc != 0
  become: "{{ ansible_user_id != 'root' }}" 
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download docker GPG key (Debian)
  when: docker_exists.rc != 0
  become: "{{ ansible_user_id != 'root' }}"
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add docker apt repository (Debian)
  when: docker_exists.rc != 0
  become: "{{ ansible_user_id != 'root' }}"
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.sources
    mode: "0644"
    content: |
      Types: deb 
      URIs: https://download.docker.com/linux/debian
      Suites: {{ ansible_facts.lsb.codename }}
      Components: stable
      Signed-By: /etc/apt/keyrings/docker.asc

- name: Ensure apt cache is up to date after adding docker repository 
  when: docker_exists.rc != 0
  become: "{{ ansible_user_id != 'root' }}"
  ansible.builtin.apt:
    update_cache: yes

- name: Ensure docker packages is installed (Debian)
  when: docker_exists.rc != 0
  become: "{{ ansible_user_id != 'root' }}"
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io 
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure user is in docker group 
  become: "{{ ansible_user_id != 'root' }}"
  ansible.builtin.user:
    name: "{{ ansible_main_user }}"
    groups: docker
    append: yes
  #notify: reset connection
