---
common_packages:
  - git
  - neovim


  # Normal Languages
  - golang
  - python3


  # Utilities
  - kitty
  - bat
  - btop
  - fastfetch
  - nmap # For network scanning, come with ncat

darwin_common_packages:


apt_common_packages:
  - sudo
  - net-tools

  - network-manager
